In [1]:
import pandas as pd

In [5]:
df= pd.read_csv('D:/Programfile/study/streamlit_youth_consulting/data/youth_consulting.csv', index_col=0)

In [11]:
df

,지역,가족,일탈,학업진로,성,대인관계,성격,정신건강,생활습관태도,활동,PC인터넷,단순정보제공,합계
0,서울,78683,71060,119812,12610,184396,47469,129715,8272,14681,37625,54504,758827
1,부산,32947,24596,51673,9449,81800,26815,40587,5070,546,26709,21221,321413
2,대구,15972,15817,16239,1341,34811,13789,9336,2549,189,17121,9376,136540
3,인천,12063,22182,19220,2086,27718,8864,41185,821,3336,11626,13042,162143
4,광주,10480,6939,11454,1352,15044,5474,8905,826,33,16220,7794,84521
5,대전,6171,12119,10554,1560,17873,6553,15430,309,752,8866,15307,95494
6,울산,11962,8967,18731,1559,34277,10696,13658,872,215,10224,5092,116253
7,세종,881,1690,1354,171,4974,274,2093,32,2,1466,110,13047
8,경기,72369,107464,228042,10359,335253,76329,122396,14145,15593,66070,59812,1107832
9,강원,6587,8959,18253,986,16454,6465,5768,1068,3803,14565,7084,89992
10,충북,7223,20899,31540,3697,28346,8147,16050,1711,2525,19452,12463,152053
11,충남,10780,27372,75094,8754,42982,11840,15566,1796,8443,27338,11584,241549
12,전북,184650,20484,55708,1822,34220,7760,21161,1108,6719,16776,10542,360950
13,전남,146270,23685,29289,3492,20948,11453,12983,1152,2404,19804,11775,283255
14,경북,189928,9982,46845,3928,52687,17410,14830,1676,1407,25957,3996,368646
15,경남,437725,27989,103587,6032,119429,37247,44032,5605,7316,33582,18126,840670
16,제주,52314,4681,8878,857,10847,4949,7918,204,153,4727,3100,98628

In [13]:
df.loc[17] = df.iloc[0:17, :].sum()

In [14]:
df.iloc[17, 0] = '전국'

In [19]:
df.to_csv('./youth_consulting.csv')